import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
test('atomic Grooves reservation enforces total and one attempt across statuses and projects',()=>{
 const source=readFileSync(new URL('../worker/renders.js',import.meta.url),'utf8');
 const sql=source.match(/`(INSERT INTO renders[\s\S]*?ON CONFLICT\(project_id,request_key\) DO NOTHING)`/)[1];
 const script=`import sqlite3,json,sys\nsql=json.loads(sys.stdin.read())\ndef run(count,cost,quote,cap=100):\n db=sqlite3.connect(':memory:')\n db.execute('CREATE TABLE renders (id TEXT,project_id TEXT,session_id TEXT,scene_id TEXT,shot_id TEXT,request_key TEXT,request_hash TEXT,provider TEXT,model TEXT,status TEXT,estimated_cost REAL,reserved_cost REAL,input_json TEXT,created_at TEXT,updated_at TEXT,actual_cost REAL, UNIQUE(project_id,request_key))')\n db.execute('CREATE TABLE generation_jobs(project_id TEXT,actual_cost REAL,reserved_cost REAL)')\n for n in range(count):\n  db.execute('INSERT INTO renders(id,project_id,session_id,scene_id,shot_id,request_key,provider,status,actual_cost,reserved_cost) VALUES(?,?,?,?,?,?,?,?,?,?)',(str(n),'yard','session','CREATE','old',str(n),'higgsfield-kling-3-standard','failed',cost/count,0))\n args=['new','yard','session','CREATE','new','request-key','hash','higgsfield-genjutsu-motion','model',quote,quote,'{}','now','now',quote,'yard','yard',quote,cap,'session',quote,cap,0,5,0,'yard','new','','yard','new',0,'yard','yard',quote,1,'yard','session','yard','session',quote,0,'unused','unused','unused','unused',quote,'standard','pro','standard','pro',quote,2.94]\n db.execute(sql,args)\n return db.execute("SELECT COUNT(*) FROM renders WHERE id='new'").fetchone()[0]\nassert run(0,0,1.26)==1\nassert run(0,0,1.30)==1\nassert run(0,0,1.301)==0\nassert run(1,0,1.26)==0\nassert run(1,0.04,1.26)==0\nassert run(0,0,1.26,1.25)==0\nprint('atomic budget boundaries passed')\n`;
 assert.match(execFileSync('python3',['-c',script],{input:JSON.stringify(sql),encoding:'utf8'}),/passed/);
});
